apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <MANIFEST_REPOSITORY_URL>
    targetRevision: main
    path: dev/sample/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: sample
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true